# Generated by Django 2.1.7 on 2019-03-16 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.TextField(default='1600 Amphitheatre Parkway, Mountain View, CA 94043'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='avg_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
