# Generated by Django 2.1.7 on 2019-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20190316_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
